[platformio]
default_envs = devkitc1-n4
src_dir = .

[env]
platform = espressif32@^55.3.38
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit NeoPixel@^1.15.5
    https://github.com/bertrik/minishell
    thomasfredericks/MicroSlip@^0.1.9

[env:devkitc1-n4]
board = esp32-c5-devkitc1-n4

; When using the USB-UART port, DTR and RTS must both be set to 0, to avoid keeping the board in reset
; monitor_dtr = 0
; monitor_rts = 0

; enable these flags to use the USB-native port
upload_port = /dev/ttyACM0
build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
